### ISSUE TITLE
open aragon DAO in new window upon successful execution

### ISSUE THREAD

**Issue by divine-comedian** [BlossomLabs/evmcrispr-terminal#2]
When I successfully run a command in evm-crispr it redirects me in the same window to the aragon DAO where the vote has been created. This can be frustrating because I lose my window from where I was currently working, also because there is no local storage of what has been input it is impossible to recover your code you put into the terminal. 

I would suggest opening the aragon DAO in a new window and as well to implement some sort of local storage so we don't lose what's already been put into the terminal. 

ALSO it would be awesome to redirect automaticall into blossom's redundant URL of xdai aragon instead of the default aragon URL

**Comment by sembrestels** [comment]
Thanks for the feedback, the issue is solved in https://github.com/BlossomLabs/evmcrispr-terminal/commit/9149579963f726e9e4091635a4dc77b4bf4b96c4.

We improved the performance of aragon.1hive.org, so we can keep the blossom's redundant URL for backup.
