### ISSUE TITLE
add information to votes created with evm-crispr

### ISSUE THREAD

**Issue by divine-comedian** [BlossomLabs/evmcrispr-terminal#3]
We should add some information to votes we create with EVM-crispr. This can cause security issues within a DAO because until the vote is executed it is impossible to verify what the vote is proposing to do. An obvious problem would be that anyone can create a vote on the DAO and invent any story to what it is for which may not be the truth. 

A simple solution would be to output what was input into the terminal into the vote. For example I created this vote just now on my DAO 
![image](https://user-images.githubusercontent.com/67759413/143074493-755bf08c-69a5-4c20-a431-5da574f55cec.png)

and the script is in the description on the vote somewhere 
```
act 0xb85431ead6471b6fb83afe797b03578c84b24af6 0xf11aC05c97F8845f6b974e9e327129d36683cC90 allocateMany(address[],uint256[]) [0x826976d7C600d45FB8287CA1d7c76FC8eb732030,0x81443887E6Aef75de940B7244783f896B1c034Ca] [10000000000000000000,10000000000000000000]
```

if it's too long maybe create a link to an ipfs hash or something? The critical issue here is that there is no transparent way to view these scripts before they are executed.

**Comment by sembrestels** [comment]
I totally feel you. We can not solve this within evmcrispr, and it's more difficult than it seems, although we plan to improve the radspec support in the future with a radspec registry. Unfortunately it will take time.
